# Number of replicas for Kibana
replicaCount: 1  # Only one replica for simplicity, increase if needed

# Kibana image configuration (use the same version as Elasticsearch)
image:
  repository: "docker.elastic.co/kibana/kibana"
  pullPolicy: IfNotPresent
  tag: "7.16.2"  # Ensure the Kibana version matches Elasticsearch version

# Custom application name and namespace to match Elasticsearch
appName: kibana
namespace: logging  # Ensure it matches Elasticsearch's namespace

# Image pull secrets for private registries (if required)
imagePullSecrets: []

# Service configuration
service:
  type: LoadBalancer  
  port: 5601

# Elasticsearch service name (for Kibana to connect to Elasticsearch)
elasticsearchHosts: "http://elasticsearch:9200"  # Use the service name of Elasticsearch in the 'logging' namespace

# Persistence settings (optional for Kibana)
persistence:
  enabled: false  # Kibana does not need persistent storage unless required for caching

# Resource limits and requests (aligned with Elasticsearch's resource settings)
resources:
  limits:
    cpu: "1"
    memory: "2Gi"
  requests:
    cpu: "500m"
    memory: "1Gi"

# Liveness and readiness probes
livenessProbe:
  httpGet:
    path: /api/status  # Kibana's status endpoint
    port: 5601
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /api/status  # Kibana's status endpoint
    port: 5601
  initialDelaySeconds: 30
  periodSeconds: 10

# Autoscaling configuration (optional for Kibana)
autoscaling:
  enabled: false  # Adjust if you want auto-scaling for Kibana
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80  # Scaling based on CPU utilization

# Ingress configuration for external access (optional, disable for internal use only)
ingress:
  enabled: false  # Use ClusterIP unless external access is needed
  annotations: {}
  hosts:
    - host: kibana.local  # Change this if you enable ingress for external access
      paths:
        - path: /
          pathType: Prefix
  tls: []  # Enable TLS if needed for external access







